export const drivers = [
  { id: 0, name: "ทั้งหมด", shortName: "รวม", status: "active" },
  { id: 1, name: "สมชาย", shortName: "สมชาย", status: "active" },
  { id: 2, name: "วิชัย", shortName: "วิชัย", status: "active" },
  { id: 3, name: "นัท", shortName: "นัท", status: "active" },
  { id: null, name: "ยังไม่มอบหมาย", shortName: "ยังไม่มอบหมาย", status: "pending" },
];

export const fallbackOrders = [
  {
    id: 1,
    order_no: "OD690506-001",
    customer_id: 1,
    customer_name: "คุณสมชาย ใจดี",
    phone: "081-234-5678",
    delivery_address: "หมู่บ้านนนทรีซิตี้ 3",
    delivery_time: "09:15",
    status: "รอส่ง",
    payment_status: "รอชำระ",
    payment_method: "เงินสด",
    total_amount: 760,
    assigned_driver_id: 1,
    customer_latitude: 13.9121827,
    customer_longitude: 100.4988192,
    items: [{ product_name: "แก๊ส 15 กก.", quantity: 2, unit_price: 380 }],
  },
  {
    id: 2,
    order_no: "OD690506-002",
    customer_id: 2,
    customer_name: "ร้านอาหารครัวคุณนิด",
    phone: "089-111-2233",
    delivery_address: "ถ.ติวานนท์ ปากเกร็ด",
    delivery_time: "09:30",
    status: "กำลังส่ง",
    payment_status: "เก็บเงินปลายทาง",
    payment_method: "โอน",
    total_amount: 1450,
    assigned_driver_id: 2,
    customer_latitude: 13.9051712,
    customer_longitude: 100.5214925,
    items: [{ product_name: "แก๊ส 48 กก.", quantity: 1, unit_price: 1450 }],
  },
  {
    id: 3,
    order_no: "OD690506-003",
    customer_id: 4,
    customer_name: "ร้านกาแฟ Tree House",
    phone: "086-222-1111",
    delivery_address: "โครงการ The Connect",
    delivery_time: "10:00",
    status: "รอส่ง",
    payment_status: "เครดิต",
    payment_method: "เครดิต",
    total_amount: 380,
    assigned_driver_id: null,
    customer_latitude: 13.8938642,
    customer_longitude: 100.5156304,
    items: [{ product_name: "แก๊ส 15 กก.", quantity: 1, unit_price: 380 }],
  },
];
